---
config:
  theme: neo-dark
---
sequenceDiagram
    participant browser
    participant server
    
    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/spa
    activate server
    server-->>browser: The server returns HTML document
    Note right of browser: The server response with HTTP 200 code
    deactivate server
    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/main.css
    activate server
    server-->>browser: the server returns css file
    Note right of browser: The server response with HTTP 200 code
    deactivate server
    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/spa.js
    activate server
    server-->>browser: the server returns JavaScript file
    deactivate server
    Note right of browser: The browser starts executing the JavaScript code that fetches the JSON from the server
    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/data.json
    activate server
    server-->>browser: The server returns the JSON content
    deactivate server
    Note right of browser: The browser executes the callback function that renders the notes
    browser->>server: POST https://studies.cs.helsinki.fi/exampleapp/new_note_spa
    Note right of browser: The user fill the textfield with "uwu" and click save (sending new note to server).
    server-->>browser: The server return the code 201 Created {content: "uwu", date: "2025-01-23T21:30:53.040Z"}
    Note right of browser: The browser executes the callback function that redraw the notes with data recieved from server.
